name: Docker Build Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Build Pass Test
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
